name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request_target:
  push:
    branches:
      - main
env:
  CSP_API_URL: https://console.cloud.vmware.com
  CSP_API_TOKEN: ${{ secrets.CSP_API_TOKEN }}
  VIB_PUBLIC_URL: https://cp.bromelia.vmware.com

jobs:
  test-action: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Prepare
        id: prep
        run: |
          echo "${{ github.repository }}"
          cat README.MD
      - uses: mpermar/vib-action@main
        with:
          path: '/'
          config: '.cp'
          pipeline: 'cp-pipeline.json'
